// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/Header.vue')['default']
    PostButton: typeof import('./src/components/PostButton.vue')['default']
  }
}

export { }
